version: '3.8'

services:
  hora-clima-app:
    build: .
    container_name: hora-clima-landing
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - hora-clima-network

networks:
  hora-clima-network:
    driver: bridge 